### ISSUE TITLE
Where is the documentation for configuration?

### ISSUE THREAD

**Issue by juxuanu** [JoseExposito/touche#13]
![image](https://user-images.githubusercontent.com/24759034/109493035-3057c280-7a8c-11eb-87c2-092cc3322594.png)

This isn't working. How do I know what to type?

**Comment by JoseExposito** [comment]
Hi!

The documentation is here:
https://github.com/JoseExposito/touchegg#keyboard-shortcut-send_keys

I already created a feature request https://github.com/JoseExposito/touche/issues/1 because, as it is at the moment, it is pretty confusing.

Anyway, you need to use:
Modifiers: Alt_L
Keys: Right or Left
