### ISSUE TITLE
Crash when only one global setting is available

### ISSUE THREAD

**Issue by Namerif** [JoseExposito/touche#6]
### Describe the bug
I've installed the last version of Touche, a .deb package taken from release in this repository. But when I'm trying to launch it by typing `com.github.joseexposito.touche` in terminal, it gives me some errors and no window is opened. The Touchegg itself works perfectly.

### Logs
[touche.log](https://github.com/JoseExposito/touche/files/5964867/touche.log)
[touchegg.conf.txt](https://github.com/JoseExposito/touche/files/5964873/touchegg.conf.txt)

### Your environment
 * Version of Touché: 1.0.2
 * Operating System: Linux Mint 20.1
 * Desktop Environment: Cinnamon
 * Installation method: Debian package

**Comment by JoseExposito** [comment]
Hi! Thank you for the bug report.

I just fixed the issue, it'll be fixed in the next release.

However, it looks like you are using an old version of Touchégg (v1) and this app is only compatible with v2.
Make sure delete your current config (/home/namerif/.config/touchegg/touchegg.conf) and install the last package from:
https://github.com/JoseExposito/touchegg/releases

Thanks again!

**Comment by Namerif** [comment]
Hi, thank you for developing such a useful and handy app too. I've just installed the latest version of Touchégg as you said, but I don't really understand why do I need to remove my config. Can you explain it, please?

**Comment by JoseExposito** [comment]
Yes, your current config was generated by Touchégg v1.
Touchégg v2 introduced some braking changes in the configuration file and it will fail with your current configuration.
That's why I recommended you to delete it and reconfigure it using the latest version. 

Sorry for the inconvenient caused, I know that configuring it can be a pain, hopefully Touché helps a bit there.
