### ISSUE TITLE
Swipe with 3 fingers not working on smaller touchpads

### ISSUE THREAD

**Issue by lcsvcn** [JoseExposito/touche#63]
Swipe with 3 fingers not working on my touch pad - It is not working, because there is not enought height to make a complete swipe up gesture, even if I start from the bottom of the touchpad.

The command is identified, but since my touch pad is not big enought to make a complete motion, the animation get stuck in the middle.

My notebook is samsung ativ book 6, the touch pad is not that small, but not as big as a Macbook and other newers notebooks.

The swipe left and right works perfect.

Can u please add a way to toggle sensitity of the gestures, so I can customize the gesture sensibility?

**Comment by JoseExposito** [comment]
Could you add your system information (distro version), `touchegg --version` and `libinput --version`, please?

It is most likely a duplicated of https://github.com/JoseExposito/touchegg/issues/542#issuecomment-948767422

**Comment by lcsvcn** [comment]
![Screenshot from 2022-03-06 22-40-40](https://user-images.githubusercontent.com/6011385/156953578-7e4e5ac1-edef-4d83-a49d-ac17b9dd13f5.png)

**Comment by JoseExposito** [comment]
Thanks for the info. Yes, it is the same issue explained here:
https://github.com/JoseExposito/touchegg/issues/542#issuecomment-948767422

The problem is that the deb package available in the downloads page is compiled for Debian. However, your distro uses a newer  version of libinput, creating issues.

I don't know if you can use PPAs on Kali Linux. If not, you'd need to compile Touchegg yourself:
https://github.com/JoseExposito/touchegg/blob/master/HACKING.md#compilation

Since it looks like many distros are having the same issue, I just opened an issue to create Deb packages for Debian Sid: https://github.com/JoseExposito/touchegg/issues/567
