### ISSUE TITLE
Allow to configure the gestures' sensitivity

### ISSUE THREAD

**Issue by ema2159** [JoseExposito/touche#81]
Hola José!  Thanks for the awesome package. It is awesome to finally be able to have this type of feature in Linux, so thank you for that. 

There is a thing that I think would be good to allow to configure from Touché. That would be the motion thresholds to start and end the animations. As a power user, it is relatively straightforward to go to the `/lib/systemd/system/touchegg.service` file, modify the thresholds from there, and restart the daemo, but for a regular user, it may be a little bit complicated and confusing.

Do you think this is something that it makes sense to implement such a solution?

**Comment by JoseExposito** [comment]
Hi!

As described in the documentation:
https://github.com/JoseExposito/touchegg#daemon-configuration

This feature is present only because the size of certain touchpads is unknown. It is mean to be used only in those cases and most touchpads should provide a decent start/end threshold by default.

In addition, editing  the `/lib/systemd/system/touchegg.service` file required root permissions, and I'd prefer not to add such complexity to the app... Plus I'm not even sure if it is possible to request root access from a Flatpak package.

So, for the moment I don't think that it makes sense to implement this feature. As you mentioned it is a power user feature, so most power users should feel confident editing a text file from the command line.

**Comment by ema2159** [comment]
Thanks for your quick answer! That pretty much clarifies it.

I installed touchegg on a Thinkpad and on an MSI laptop. In the Thinkpad it worked nicely but in the MSI didn't because of this sensitivity issue, but I guess it's just because it doesn't provide proper parameters for it's track pad.
